gText_Birch_Welcome::
	.string "EVER GRANDE CITY...\p"
	.string "It doesn't seem to live up to its,\p"
	.string "name today, does it?\p"
	.string "But believe it or not, that city was once\n"
	.string "the shining pride of HOENN.\p"
	.string "No other city on the mainland or\n"
	.string "the islands could compare.\p"
	.string "In fact, for the longest time, it\n"
	.string "was its own kingdom.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "It was home to both people and POKéMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "But then, one day, it was brought\n"
	.string "to ruin. It was destroyed,\n"
	.string "all due to the hubris of a few.\p"
	.string "Its former glory would never be returned.\l"
	.string "But don't look at me like that - \l"
	.string "it's not a sad story!\l"
	.string "Rather, it's the story of friendship,\n"
	.string "and of how something new emerged from the ruins.\p"
	.string "Sit down a moment.\n"
	.string "I'll tell it to you.\p"
	.string "It begins with the one they called\n"
	.string "the Heir...\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
